#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib.sh
. "${SCRIPT_DIR}/lib.sh"

usage() {
  cat <<'EOF'
Usage:
  render.sh --network <mainnet|hoodi> --output-dir <path> [--overlay-profiles <csv>] [--force]
  render.sh --cluster-file <path> --host-file <path> --output-dir <runtime-path> [--overlay-profiles <csv>] [--force]
  render.sh --cluster-file <path> --hosts-file <path> --output-dir <path> [--host-name <name>] [--overlay-profiles <csv>] [--force]

Examples:
  ./render.sh --network mainnet --output-dir /tmp/cdvn-mainnet --overlay-profiles web3signer
  ./render.sh --cluster-file ../inventory/cluster.example.yml --host-file ../inventory/operator-1.local.example.yml --output-dir /tmp/cdvn-operator-1-runtime --force
  ./render.sh --cluster-file ../inventory/cluster.example.yml --hosts-file ../inventory/hosts.example.yml --output-dir /tmp/cdvn-bundle --force
EOF
}

NETWORK=""
OUTPUT_DIR=""
CLUSTER_FILE=""
HOST_FILE=""
HOSTS_FILE=""
HOST_NAME_FILTER=""
OVERLAY_PROFILES_ARG=""
FORCE=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --network)
      NETWORK="${2:-}"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="${2:-}"
      shift 2
      ;;
    --cluster-file)
      CLUSTER_FILE="${2:-}"
      shift 2
      ;;
    --host-file)
      HOST_FILE="${2:-}"
      shift 2
      ;;
    --hosts-file)
      HOSTS_FILE="${2:-}"
      shift 2
      ;;
    --host-name)
      HOST_NAME_FILTER="${2:-}"
      shift 2
      ;;
    --overlay-profile|--overlay-profiles)
      OVERLAY_PROFILES_ARG="${2:-}"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_baseline

if [ -z "${OUTPUT_DIR}" ]; then
  usage >&2
  exit 1
fi

if [ -d "${OUTPUT_DIR}" ] && [ "${FORCE}" -ne 1 ]; then
  if find "${OUTPUT_DIR}" -mindepth 1 -maxdepth 1 -print -quit | grep -q .; then
    echo "Output directory is not empty: ${OUTPUT_DIR}. Re-run with --force to replace it." >&2
    exit 1
  fi
fi

mkdir -p "${OUTPUT_DIR}"

PINNED_BASELINE_REF="$(get_pinned_baseline_ref)"

resolve_env_sample() {
  local network="$1"
  local env_sample=".env.sample.${network}"
  if [ -n "${CLUSTER_COMPOSE_ENV_SAMPLE:-}" ]; then
    env_sample="${CLUSTER_COMPOSE_ENV_SAMPLE}"
  fi
  printf '%s/%s' "${UPSTREAM_DIR}" "${env_sample}"
}

prepare_runtime_dir() {
  local runtime_dir="$1"
  local env_sample_file="$2"

  mkdir -p "${runtime_dir}"
  rsync -a --delete \
    --exclude data/ \
    --exclude .charon/ \
    --exclude jwt/jwt.hex \
    --exclude charon-artifacts-staging.env \
    --exclude validator-pubkeys.txt \
    "${UPSTREAM_DIR}/" "${runtime_dir}/"
  cp "${env_sample_file}" "${runtime_dir}/.env"

  mkdir -p "${runtime_dir}/jwt" "${runtime_dir}/.charon" "${runtime_dir}/data"
}

generate_compose_override() {
  local runtime_dir="$1"
  local overlay_profiles="$2"
  local override_file="${runtime_dir}/docker-compose.override.yml"
  local overlay fragment any_fragment

  any_fragment=0
  {
    printf '# Generated by infra/obol-cdvn/scripts/render.sh\n'
    printf 'services:\n'
    for overlay in $(printf '%s' "$(csv_normalize "$overlay_profiles")" | tr ',' ' '); do
      fragment="${OVERLAYS_DIR}/${overlay}/docker-compose.services.yml"
      if [ -f "$fragment" ]; then
        cat "$fragment"
        printf '\n'
        any_fragment=1
      fi
    done
    if [ "$any_fragment" -eq 0 ]; then
      printf '  # No overlay compose services selected.\n'
    fi
  } > "${override_file}"
}

apply_overlay_assets() {
  local runtime_dir="$1"
  local env_file="$2"
  local overlay_profiles="$3"
  local overlay

  for overlay in $(printf '%s' "$(csv_normalize "$overlay_profiles")" | tr ',' ' '); do
    apply_env_defaults "${env_file}" "${OVERLAYS_DIR}/${overlay}/env.defaults"

    case "$overlay" in
      web3signer)
        cp "${OVERLAYS_DIR}/web3signer/compose-vc.yml" "${runtime_dir}/compose-vc.yml"
        mkdir -p "${runtime_dir}/lodestar"
        cp "${OVERLAYS_DIR}/web3signer/lodestar/run.sh" "${runtime_dir}/lodestar/run.sh"
        chmod +x "${runtime_dir}/lodestar/run.sh"
        ;;
      observability)
        RUNTIME_VC_METRICS_TARGET="vc-lodestar:$(read_env_value "${env_file}" "VC_PORT_METRICS")"
        [ -n "${RUNTIME_VC_METRICS_TARGET#vc-lodestar:}" ] || RUNTIME_VC_METRICS_TARGET="vc-lodestar:5064"
        mkdir -p "${runtime_dir}/prometheus"
        render_template \
          "${OVERLAYS_DIR}/observability/prometheus/prometheus.yml.example.tpl" \
          "${runtime_dir}/prometheus/prometheus.yml.example"
        ;;
    esac
  done

  generate_compose_override "${runtime_dir}" "${overlay_profiles}"
}

write_runtime_notes() {
  local runtime_dir="$1"
  local overlay_profiles="$2"
  local metadata_file="$3"
  local rendered_at

  rendered_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  cat > "${runtime_dir}/RENDERED_BY_CONTROL_PLANE.txt" <<EOF
Pinned CDVN baseline rendered from:
$(cat "${VERSION_FILE}")

NETWORK=${RUNTIME_NETWORK}
CLUSTER_NAME=${RUNTIME_CLUSTER_NAME}
HOST_NAME=${RUNTIME_HOST_NAME}
OVERLAY_PROFILES=${overlay_profiles}

This output is safe to review and roll out as a base runtime, but not ready for validator operation until:
1. A fresh jwt/jwt.hex is generated on the deployment target.
2. The selected overlays are verified against the rendered runtime before rollout.
3. Approved .charon artifacts are staged on the operator host after rollout with stage-charon-artifacts.sh --runtime-dir.
EOF

  cat > "${runtime_dir}/OVERLAY_TODO.md" <<EOF
# Overlay TODO

Selected overlays: ${overlay_profiles}

Required next steps before validating:

1. Run verify.sh against the rendered runtime and obtain a rollout approval manifest.
2. Roll out the rendered runtime without .charon artifacts.
3. Generate jwt/jwt.hex on the deployment target.
4. Stage approved .charon artifacts on the operator host with stage-charon-artifacts.sh --runtime-dir.
5. Verify Web3Signer reachability, remote signer pubkey visibility, Prometheus, Loki, Tempo, and alert routing from the deployed host.
EOF

  cat > "${metadata_file}" <<EOF
CLUSTER_NAME=${RUNTIME_CLUSTER_NAME}
HOST_NAME=${RUNTIME_HOST_NAME}
HOST_ADDRESS=${RUNTIME_HOST_ADDRESS}
SSH_USER=${RUNTIME_SSH_USER}
SSH_TARGET=${RUNTIME_SSH_TARGET}
NETWORK=${RUNTIME_NETWORK}
BASELINE_REF=${PINNED_BASELINE_REF}
OVERLAY_PROFILES=${overlay_profiles}
APPROVAL_POLICY=${RUNTIME_APPROVAL_POLICY}
SERVICE_OWNER=${RUNTIME_SERVICE_OWNER}
DEPLOYMENT_PATH=${RUNTIME_DEPLOYMENT_PATH}
HEALTH_SYNC_URL=${RUNTIME_HEALTH_SYNC_URL}
RENDERED_AT=${rendered_at}
EOF
}

apply_runtime_env() {
  local env_file="$1"
  local overlay_profiles="$2"
  local compose_project_name charon_network

  compose_project_name="$(sanitize_name "${RUNTIME_CLUSTER_NAME}-${RUNTIME_HOST_NAME}")"
  [ -n "${compose_project_name}" ] || compose_project_name="$(sanitize_name "${RUNTIME_HOST_NAME}")"
  charon_network="${compose_project_name}_dvnode"

  upsert_env_value "${env_file}" "NETWORK" "${RUNTIME_NETWORK}"
  upsert_env_value "${env_file}" "COMPOSE_PROJECT_NAME" "${compose_project_name}"
  upsert_env_value "${env_file}" "CHARON_DOCKER_NETWORK" "${charon_network}"
  upsert_env_value "${env_file}" "CLUSTER_NAME" "${RUNTIME_CLUSTER_NAME}"
  upsert_env_value "${env_file}" "CLUSTER_PEER" "${RUNTIME_CLUSTER_PEER}"
  upsert_env_value "${env_file}" "CHARON_NICKNAME" "${RUNTIME_CHARON_NICKNAME}"
  upsert_env_value "${env_file}" "CHARON_P2P_EXTERNAL_HOSTNAME" "${RUNTIME_CHARON_EXTERNAL_HOSTNAME}"
  upsert_env_value "${env_file}" "SERVICE_OWNER" "${RUNTIME_SERVICE_OWNER}"
  upsert_env_value "${env_file}" "MONITORING_PORT_GRAFANA" "${RUNTIME_GRAFANA_PORT}"
  upsert_env_value "${env_file}" "PROMETHEUS_PORT_HTTP" "${RUNTIME_PROMETHEUS_PORT}"
  upsert_env_value "${env_file}" "CDVN_BASELINE_VERSION" "${PINNED_BASELINE_REF}"
  upsert_env_value "${env_file}" "CDVN_OVERLAY_PROFILES" "${overlay_profiles}"
  upsert_env_value "${env_file}" "CDVN_HOST_NAME" "${RUNTIME_HOST_NAME}"
  upsert_env_value "${env_file}" "CDVN_HOST_ADDRESS" "${RUNTIME_HOST_ADDRESS}"
  upsert_env_value "${env_file}" "CDVN_HOST_REGION" "${RUNTIME_HOST_REGION}"
  upsert_env_value "${env_file}" "WEB3SIGNER_URL" "${RUNTIME_WEB3SIGNER_URL}"
  upsert_env_value "${env_file}" "WEB3SIGNER_METRICS_TARGET" "${RUNTIME_WEB3SIGNER_METRICS_TARGET}"
  upsert_env_value "${env_file}" "WEB3SIGNER_FETCH" "${RUNTIME_WEB3SIGNER_FETCH}"
  upsert_env_value "${env_file}" "WEB3SIGNER_FETCH_INTERVAL_MS" "${RUNTIME_WEB3SIGNER_FETCH_INTERVAL_MS}"
  upsert_env_value "${env_file}" "FEE_RECIPIENT_ADDRESS" "${RUNTIME_FEE_RECIPIENT_ADDRESS}"
  upsert_env_value "${env_file}" "CDVN_HEALTH_SYNC_URL" "${RUNTIME_HEALTH_SYNC_URL}"
}

render_runtime() {
  local runtime_dir="$1"
  local overlay_profiles="$2"
  local env_sample_file="$3"
  local metadata_file="${runtime_dir}/render-metadata.env"

  prepare_runtime_dir "${runtime_dir}" "${env_sample_file}"
  apply_overlay_assets "${runtime_dir}" "${runtime_dir}/.env" "${overlay_profiles}"
  apply_runtime_env "${runtime_dir}/.env" "${overlay_profiles}"
  write_runtime_notes "${runtime_dir}" "${overlay_profiles}" "${metadata_file}"
}

if [ -n "${CLUSTER_FILE}" ]; then
  if [ ! -f "${CLUSTER_FILE}" ]; then
    echo "Cluster file not found: ${CLUSTER_FILE}" >&2
    exit 1
  fi
  if [ -n "${HOST_FILE}" ] && [ -n "${HOSTS_FILE}" ]; then
    echo "Use either --host-file for operator-local render or --hosts-file for cluster bundle render, not both." >&2
    exit 1
  fi
  if [ -n "${HOST_FILE}" ] && [ -n "${HOST_NAME_FILTER}" ]; then
    echo "--host-name is only valid with --hosts-file. Put the operator identity in --host-file instead." >&2
    exit 1
  fi
  if [ -z "${HOST_FILE}" ] && [ -z "${HOSTS_FILE}" ]; then
    echo "Cluster render requires either --host-file or --hosts-file." >&2
    exit 1
  fi
  if [ -n "${HOSTS_FILE}" ] && [ ! -f "${HOSTS_FILE}" ]; then
    echo "Hosts file not found: ${HOSTS_FILE}" >&2
    exit 1
  fi
  if [ -n "${HOST_FILE}" ] && [ ! -f "${HOST_FILE}" ]; then
    echo "Host file not found: ${HOST_FILE}" >&2
    exit 1
  fi

  load_cluster_config "${CLUSTER_FILE}"

  [ -n "${NETWORK}" ] || NETWORK="${CLUSTER_NETWORK}"
  [ -n "${NETWORK}" ] || { echo "Cluster render requires a network value." >&2; exit 1; }

  if [ -n "${CLUSTER_BASELINE_VERSION}" ] && [ "${CLUSTER_BASELINE_VERSION}" != "${PINNED_BASELINE_REF}" ]; then
    echo "Cluster baselineVersion (${CLUSTER_BASELINE_VERSION}) does not match pinned baseline (${PINNED_BASELINE_REF})." >&2
    exit 1
  fi

  if [ -n "${OVERLAY_PROFILES_ARG}" ]; then
    OVERLAY_PROFILES="$(csv_normalize "${OVERLAY_PROFILES_ARG}")"
  else
    OVERLAY_PROFILES="$(csv_normalize "${CLUSTER_OVERLAY_PROFILES}")"
  fi
  [ -n "${OVERLAY_PROFILES}" ] || OVERLAY_PROFILES="web3signer"

  ENV_SAMPLE_FILE="$(resolve_env_sample "${NETWORK}")"
  if [ ! -f "${ENV_SAMPLE_FILE}" ]; then
    echo "Unsupported network '${NETWORK}'. Expected env sample at ${ENV_SAMPLE_FILE}." >&2
    exit 1
  fi

  if [ -n "${HOST_FILE}" ]; then
    load_host_config "${HOST_FILE}"

    RUNTIME_CLUSTER_NAME="${CLUSTER_MONITORING_NAME}"
    RUNTIME_NETWORK="${NETWORK}"
    RUNTIME_HOST_NAME="${HOST_NAME}"
    RUNTIME_HOST_ADDRESS="${HOST_ADDRESS}"
    RUNTIME_HOST_REGION="${HOST_REGION}"
    RUNTIME_CLUSTER_PEER="${HOST_MONITORING_PEER:-${HOST_NAME}}"
    RUNTIME_CHARON_NICKNAME="${HOST_NICKNAME:-${HOST_NAME}}"
    RUNTIME_CHARON_EXTERNAL_HOSTNAME="${HOST_EXTERNAL_HOSTNAME:-${HOST_ADDRESS}}"
    RUNTIME_SERVICE_OWNER="${CLUSTER_SERVICE_OWNER}"
    RUNTIME_WEB3SIGNER_URL="${CLUSTER_WEB3SIGNER_URL:-http://host.docker.internal:9000}"
    RUNTIME_WEB3SIGNER_METRICS_TARGET="${CLUSTER_WEB3SIGNER_METRICS_TARGET:-host.docker.internal:9000}"
    RUNTIME_WEB3SIGNER_FETCH="${CLUSTER_WEB3SIGNER_FETCH}"
    RUNTIME_WEB3SIGNER_FETCH_INTERVAL_MS="${CLUSTER_WEB3SIGNER_FETCH_INTERVAL_MS}"
    RUNTIME_FEE_RECIPIENT_ADDRESS="${CLUSTER_FEE_RECIPIENT_ADDRESS:-0x0000000000000000000000000000000000000000}"
    RUNTIME_HEALTH_SYNC_URL="${CLUSTER_HEALTH_SYNC_URL}"
    RUNTIME_GRAFANA_PORT="${HOST_GRAFANA_PORT:-3000}"
    RUNTIME_PROMETHEUS_PORT="${HOST_PROMETHEUS_PORT:-9090}"
    RUNTIME_DEPLOYMENT_PATH="${HOST_DEPLOYMENT_PATH:-${CLUSTER_DEPLOYMENT_ROOT}}"
    RUNTIME_APPROVAL_POLICY="${CLUSTER_APPROVAL_POLICY:-rollout}"
    RUNTIME_SSH_USER="${HOST_SSH_USER}"
    RUNTIME_SSH_TARGET=""
    if [ -n "${RUNTIME_SSH_USER}" ] && [ -n "${RUNTIME_HOST_ADDRESS}" ]; then
      RUNTIME_SSH_TARGET="${RUNTIME_SSH_USER}@${RUNTIME_HOST_ADDRESS}"
    fi

    render_runtime "${OUTPUT_DIR}" "${OVERLAY_PROFILES}" "${ENV_SAMPLE_FILE}"
    echo "Rendered operator runtime for ${HOST_NAME} to ${OUTPUT_DIR}"
    exit 0
  fi

  parse_hosts_file "${HOSTS_FILE}"

  if [ -n "${HOST_NAME_FILTER}" ]; then
    HOST_INDEX="$(find_host_index "${HOST_NAME_FILTER}")" || {
      echo "Host '${HOST_NAME_FILTER}' not found in ${HOSTS_FILE}" >&2
      exit 1
    }
    HOST_INDICES="${HOST_INDEX}"
  else
    HOST_INDICES="$(seq 0 $((HOST_COUNT - 1)))"
  fi

  ROOT_METADATA_FILE="${OUTPUT_DIR}/render-bundle.env"
  mkdir -p "${OUTPUT_DIR}/hosts"
  cat > "${ROOT_METADATA_FILE}" <<EOF
CLUSTER_NAME=${CLUSTER_NAME}
NETWORK=${NETWORK}
BASELINE_REF=${PINNED_BASELINE_REF}
OVERLAY_PROFILES=${OVERLAY_PROFILES}
HOST_COUNT=${HOST_COUNT}
APPROVAL_POLICY=${CLUSTER_APPROVAL_POLICY}
EOF

  for index in ${HOST_INDICES}; do
    load_host_record "${index}"

    RUNTIME_CLUSTER_NAME="${CLUSTER_MONITORING_NAME}"
    RUNTIME_NETWORK="${NETWORK}"
    RUNTIME_HOST_NAME="${HOST_NAME}"
    RUNTIME_HOST_ADDRESS="${HOST_ADDRESS}"
    RUNTIME_HOST_REGION="${HOST_REGION}"
    RUNTIME_CLUSTER_PEER="${HOST_MONITORING_PEER:-${HOST_NAME}}"
    RUNTIME_CHARON_NICKNAME="${HOST_NICKNAME:-${HOST_NAME}}"
    RUNTIME_CHARON_EXTERNAL_HOSTNAME="${HOST_EXTERNAL_HOSTNAME:-${HOST_ADDRESS}}"
    RUNTIME_SERVICE_OWNER="${CLUSTER_SERVICE_OWNER}"
    RUNTIME_WEB3SIGNER_URL="${CLUSTER_WEB3SIGNER_URL:-http://host.docker.internal:9000}"
    RUNTIME_WEB3SIGNER_METRICS_TARGET="${CLUSTER_WEB3SIGNER_METRICS_TARGET:-host.docker.internal:9000}"
    RUNTIME_WEB3SIGNER_FETCH="${CLUSTER_WEB3SIGNER_FETCH}"
    RUNTIME_WEB3SIGNER_FETCH_INTERVAL_MS="${CLUSTER_WEB3SIGNER_FETCH_INTERVAL_MS}"
    RUNTIME_FEE_RECIPIENT_ADDRESS="${CLUSTER_FEE_RECIPIENT_ADDRESS:-0x0000000000000000000000000000000000000000}"
    RUNTIME_HEALTH_SYNC_URL="${CLUSTER_HEALTH_SYNC_URL}"
    RUNTIME_GRAFANA_PORT="${HOST_GRAFANA_PORT:-3000}"
    RUNTIME_PROMETHEUS_PORT="${HOST_PROMETHEUS_PORT:-9090}"
    RUNTIME_DEPLOYMENT_PATH="${HOST_DEPLOYMENT_PATH:-${CLUSTER_DEPLOYMENT_ROOT}}"
    RUNTIME_APPROVAL_POLICY="${CLUSTER_APPROVAL_POLICY:-rollout}"
    RUNTIME_SSH_USER="${HOST_SSH_USER}"
    RUNTIME_SSH_TARGET=""
    if [ -n "${RUNTIME_SSH_USER}" ] && [ -n "${RUNTIME_HOST_ADDRESS}" ]; then
      RUNTIME_SSH_TARGET="${RUNTIME_SSH_USER}@${RUNTIME_HOST_ADDRESS}"
    fi

    render_runtime "${OUTPUT_DIR}/hosts/${HOST_NAME}/runtime" "${OVERLAY_PROFILES}" "${ENV_SAMPLE_FILE}"
  done

  echo "Rendered cluster bundle to ${OUTPUT_DIR}"
  exit 0
fi

if [ -z "${NETWORK}" ]; then
  usage >&2
  exit 1
fi

OVERLAY_PROFILES="$(csv_normalize "${OVERLAY_PROFILES_ARG:-web3signer}")"
ENV_SAMPLE_FILE="${UPSTREAM_DIR}/.env.sample.${NETWORK}"
if [ ! -f "${ENV_SAMPLE_FILE}" ]; then
  echo "Unsupported network '${NETWORK}'. Expected env sample at ${ENV_SAMPLE_FILE}." >&2
  exit 1
fi

RUNTIME_CLUSTER_NAME="single-host"
RUNTIME_NETWORK="${NETWORK}"
RUNTIME_HOST_NAME="${HOST_NAME_FILTER:-operator}"
RUNTIME_HOST_ADDRESS="127.0.0.1"
RUNTIME_HOST_REGION="local"
RUNTIME_CLUSTER_PEER="${RUNTIME_HOST_NAME}"
RUNTIME_CHARON_NICKNAME="${RUNTIME_HOST_NAME}"
RUNTIME_CHARON_EXTERNAL_HOSTNAME="127.0.0.1"
RUNTIME_SERVICE_OWNER="local-operator"
RUNTIME_WEB3SIGNER_URL="http://host.docker.internal:9000"
RUNTIME_WEB3SIGNER_METRICS_TARGET="host.docker.internal:9000"
RUNTIME_WEB3SIGNER_FETCH="true"
RUNTIME_WEB3SIGNER_FETCH_INTERVAL_MS="384000"
RUNTIME_FEE_RECIPIENT_ADDRESS="0x0000000000000000000000000000000000000000"
RUNTIME_HEALTH_SYNC_URL=""
RUNTIME_GRAFANA_PORT="3000"
RUNTIME_PROMETHEUS_PORT="9090"
RUNTIME_DEPLOYMENT_PATH=""
RUNTIME_APPROVAL_POLICY="rollout"
RUNTIME_SSH_USER=""
RUNTIME_SSH_TARGET=""

render_runtime "${OUTPUT_DIR}" "${OVERLAY_PROFILES}" "${ENV_SAMPLE_FILE}"
echo "Rendered pinned CDVN baseline to ${OUTPUT_DIR}"
